she_codes_news/news/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

from .views import CategoryView, DigitalView, PhotographyView, PaintingView

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category/digital/', DigitalView.as_view(), name='digital'),
    path('category/painting/',PaintingView.as_view(), name='painting'),
    path('category/photography/',PhotographyView.as_view(), name='photography'),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    # path('favicon.png', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.png')))
    # path('account/', include('registration.urls', namespace="accounts"))
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, ChangeAccountView, AuthorView, AccountView
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views


app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/change-account/', ChangeAccountView.as_view(), name='changeAccount'),
    path('account/<int:pk>/', AccountView.as_view(), name='account'),
    path('change-password/', auth_views.PasswordChangeView.as_view(success_url='accounts/password_change/done/'), name="password_change"),
    path('author/<int:pk>', AuthorView.as_view(), name='author'),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    # this is where to add custom fields eg. add address, fave colour 
    first_name = models.CharField(max_length=20, blank=False)
    last_name = models.CharField(max_length=20, blank=True)
    profile_img = models.ImageField(upload_to='images/', null=True, blank=True, default='she_codes_news/users/static/users/images/profile_default.gif')
    email = models.EmailField(verbose_name='email', max_length=255, unique=True)

    def __str__(self):
        return self.first_name

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm
)

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'profile_img' ]


class CustomUserChangeForm(UserChangeForm):

    password = None

    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.views.generic.detail import DetailView
from django.contrib import messages

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class AccountView(generic.DetailView):
    model = CustomUser
    template_name = 'users/Account.html'

class ChangeAccountView(UpdateView):
    form_class = CustomUserChangeForm
    model = CustomUser
    success_url = reverse_lazy('news:index')
    template_name = 'users/changeAccount.html'

class AuthorView(generic.DetailView):
    template_name="users/authorStories.html"
    model = CustomUser
    context_object_name = "author"

class ChangePassword(UpdateView):
    form_class = PasswordChangeForm
    template_name = 'users/password_change_form.html'

she_codes_news/users/templates/users/Account.html
{% extends 'base.html' %}

{% load static %}

<!-- everything from h2 tag goes in content block in base template -->

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/author-styles.css' %}">
{% endblock %}

{% block content %}

<h2>Your Account</h2>

{% if request.user.is_authenticated %}
<div class="grid-container">
    <div class="grid-item">
        <div>

            <h5>Hi, {{ user.first_name }}!</h5>

            <p>We're so glad you're here. Your details are: </p>

            <p><b>ID:</b> {{ request.user.id }}</p>
            <p><b>Username:</b> {{ request.user.username }}</p>
            <p><b>Email:</b> {{ request.user.email }}</p>

        </div>

        <div class="button-box">
            <a href="{% url 'password_change' %}"><button class="my-button">Change your password</button></a>
            <a href="/users/{{ request.user.id }}/change-account/"><button class="my-button">Edit your username or email</button></a>
        </div>
    </div>
    <div class="grid-item-2">
        <!-- {% if user.profile_img %} -->
        <img src="/news/media/{{  user.profile_img  }}"">
        {% else %}
            <img src="{% static 'users/images/profile_default.gif' %}">
            <!-- <img src="../users/images/profile_default.gif"> -->
        {% endif %}  
    </div>
</div>


{% include './authorStories.html' %}


{% else %}
    <p>Whoops, looks like you don't have an account yet. Create one <a href="/users/create-account">here...</a></p>
{% endif %}

{% endblock %}


<!-- If story in all stories has author equal to username, print list here -->

she_codes_news/users/templates/users/authorStories.html
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}

<div class="container">
    <h2>Your art submissions so far, {{ object.first_name }}!</h2>
    {% if object %}
        {% for story in object.stories.all %}
        <div class="story-card" id="story-card-{{ position }}">
            <a href="{% url 'news:story' story.id %}">
                {% if story.story_img %}
                    <img src="/news/media/{{  story.story_img  }}">
                {% else %}
                    <img src="../media/images/default_story.jpg"> 
        {% endif %} 
                <div class="story-card-text">
                    <h3>{{ story.title }}</h3>
                    <h4><a href="{% url 'users:author' story.author.id %}">{{ story.author }}</a></h4>
                    <h4>{{ story.pub_date }}</h4>
                </div>
            </a>
        </div>
        {% endfor %}
    {% else %}
        <p>This author has not written any stories yet.</p>
    {% endif %}

    <div class="centred-text">
        <p>Submit another piece of art <a href="{% url 'news:newStory' %}">here!</a></p>
    </div>

</div>
{% endblock %}

she_codes_news/users/templates/users/changeAccount.html
{% extends 'base.html' %}

{% load static %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/account-styles.css' %}">
{% endblock %}

{% block content %}
<div class="grid-container">
    <div class="grid-item"><img src="https://www.indiewire.com/wp-content/uploads/2013/06/ferris-buellers-day-off.jpg?w=780"></div>
    <div class="grid-item">
        <h2>Update Account</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update Account</button>
    </div>
</form>
</div>

{% endblock %}

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}

<h2>Create Account</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="submit">Create Account</button>
</form>
{% endblock %}

she_codes_news/users/templates/users/password_change_form.html
{% extends 'base.html' %}
 
{% block title %}
    Password Change - {{ block.super }}
{% endblock %}

{% block main %}

    <div class="main">

            <p>&#187; <a href="{% url 'password_change' %}">Change Password</a> </p>

            <h3>Change Password</h3>

            <form action="{% url 'password_change' %}" method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Submit"></td>
                    </tr>
                </table>
            </form>
    </div>

{% endblock %}