she_codes_news/news/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

from .views import CategoryView, DigitalView, PhotographyView, PaintingView

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category/digital/', DigitalView.as_view(), name='digital'),
    path('category/painting/',PaintingView.as_view(), name='painting'),
    path('category/photography/',PhotographyView.as_view(), name='photography'),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    # path('favicon.png', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.png')))
    # path('account/', include('registration.urls', namespace="accounts"))
]

she_codes_news/templates/base.html
{% load static %}

<!-- BASE TEMPLATE - means don't have to rewrite head content for each other template - extend other templates from this one -->

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Isobel Young">
        <link hrzzef="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <header>
        <div id="header-text">
            <a id="header-link" href="{% url 'news:index' %}">
                <h1>SC Discovery Project</h1>
            </a>
        </div>
        <!-- include nav here -->
        {% include './nav.html' %}
    </header>

    <body>

        <div class="my-body">
    
            <!-- content blocks here -->
            {% block content %}{% endblock %}
        
        </div>
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if request.user.is_authenticated %}

        <a href="/users/account/{{ request.user.id }}">My Profile: {{ request.user.username }}</a> 
        <!-- all templates have access to request object -->
        <a href="{% url 'news:newStory' %}">New Submission</a>
        <a href="/users/{{ request.user.id }}/change-account/">Edit My Profile</a>
        <a href="{% url 'logout' %}">Logout</a>
        
    
    {% else %}

        <a href="{% url 'login' %}">Login</a>
        <a href="/users/create-account">Create Account</a>

    {% endif %}
</nav>