she_codes_news/news/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

from .views import CategoryView, DigitalView, PhotographyView, PaintingView

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category/digital/', DigitalView.as_view(), name='digital'),
    path('category/painting/',PaintingView.as_view(), name='painting'),
    path('category/photography/',PhotographyView.as_view(), name='photography'),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    # path('favicon.png', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.png')))
    # path('account/', include('registration.urls', namespace="accounts"))
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Q

art_categories = (
    "Digital",
    "Photography",
    "Painting"
)

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="stories",
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    story_img = models.ImageField(upload_to='images/', null=True, blank=True, default='/media/images/default_story.jpg') # add default image!
    category = models.CharField(max_length=200, default="Digital")


    # objects = PostManager()

# class StoryManager(models.Manager):
#     def search(self, query=None):
#         qs = self.get_queryset()
#         if query is not None:
#             or_lookup = (Q(title__icontains=query) | 
#                          Q(description__icontains=query)|
#                          Q(slug__icontains=query)
#                         )
#             qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
#         return qs

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

art_categories = (
    "Digital",
    "Photography",
    "Painting"
)

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'story_img', 'category']
        labels = {
            'title': 'Artwork Title',
            'pub_date': 'Upload Date',
            'content': 'Comments and Description',
            'story_img': 'Upload your piece!',
            'category': 'Category'
        }
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'),
            attrs={'class':'form-control', 'placeholder':'Select a date',
            'type':'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(StoryForm, self).__init__(*args, **kwargs)
        self.fields['story_img'].required = False
    

she_codes_news/news/views.py
from django.views import generic
from .models import NewsStory
from django.urls import reverse_lazy
# from .forms import StoryForm

from django.http import HttpResponse 
from django.shortcuts import render, redirect 
from .forms import *

from users.models import CustomUser

class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all().order_by('-pub_date').all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date').all()[:4] #  added order_by to sort stories by date
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date') #  added order_by to sort stories by date
        # context['by_author'] = NewsStory.objects.all().filter('author', flat=True)
        return context

    @property
    def get_auth(self, id):
        return NewsStory.objects.all().filter(author=id)

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'


class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class CategoryView(generic.ListView):
    template_name="news/storiesByCategory.html"
    model = NewsStory
    context_object_name = "story"

    def __init__(self):
        self.category = NewsStory.category

    def get_queryset(self):
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_categories'] = NewsStory.objects.all().order_by('-pub_date')
        
        context['Digital'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Digital')
        context['Digital_sneak_peek'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Digital')[:4]
        context['Photography'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Photography')
        context['Photography_sneak_peek'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Photography')[:4]
        context['Painting'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Painting')
        context['Painting_sneak_peek'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Painting')[:4]
        
        return context

class DigitalView(generic.ListView):
    template_name="news/categoryDigital.html"
    model = NewsStory
    context_object_name = "story"

    def __init__(self):
        self.category = NewsStory.category

    def get_queryset(self):
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_categories'] = NewsStory.objects.all().order_by('-pub_date')
        
        context['Digital'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Digital')
        context['Digital_sneak_peek'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Digital')[:4]
        
        return context

class PhotographyView(generic.ListView):
    template_name="news/categoryPhotography.html"
    model = NewsStory
    context_object_name = "story"

    def __init__(self):
        self.category = NewsStory.category

    def get_queryset(self):
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_categories'] = NewsStory.objects.all().order_by('-pub_date')
        
        context['Photography'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Photography')
        context['Photography_sneak_peek'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Photography')[:4]
        
        return context

class PaintingView(generic.ListView):
    template_name="news/categoryPainting.html"
    model = NewsStory
    context_object_name = "story"

    def __init__(self):
        self.category = NewsStory.category

    def get_queryset(self):
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_categories'] = NewsStory.objects.all().order_by('-pub_date')
        
        context['Painting'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Painting')
        context['Painting_sneak_peek'] = NewsStory.objects.order_by('-pub_date').filter(category__contains='Painting')[:4]
        
        return context

she_codes_news/news/templates/news/categoryDigital.html
{% extends "base.html" %}    
{% load static %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}

<h5>Digital</h5>
<div id="all-stories">

    
    {% if Digital %}
        {% for story in Digital %}
            {% include "./storyCard.html" with story=story position=forloop.counter %}
        {% endfor %}
    {% else %}
        <p>No stories for this category!</p>
    {% endif %}

</div>

{% endblock %}

she_codes_news/news/templates/news/categoryPainting.html
{% extends "base.html" %}    
{% load static %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}

<h5>Paintings</h5>
<div id="all-stories">
    
    {% if Painting %}
    {% for story in Painting %}
        {% include "./storyCard.html" with story=story position=forloop.counter %}
    {% endfor %}
    {% else %}
        <p>No stories for this category!</p>
    {% endif %}

</div>

{% endblock %}

she_codes_news/news/templates/news/categoryPhotography.html
{% extends "base.html" %}    
{% load static %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}

<h5>Photography</h5>
<div id="all-stories">

    {% if Photography %}
    {% for story in Photography %}
        {% include "./storyCard.html" with story=story position=forloop.counter %}
    {% endfor %}
    {% else %}
        <p>No stories for this category!</p>
    {% endif %}

</div>

{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% load static %}

<!-- everything from h2 tag goes in content block in base template -->

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/new-story-styles.css' %}">
{% endblock %}

{% block content %}

<div class="header-img"></div>

{% if request.user.is_authenticated %}

<div class="grid-container">
   
    <div class="grid-item"><h2 id="new-story-h2">Show us what you got.</h2></div>
    
        <div class="grid-item">
        
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{ form.as_p }}
            <p>Please note for categories, enter exactly one of the following options:</p>
            <p>1. Digital</p>
            <p>2. Photography</p>
            <p>3. Painting</p>
            <button type="submit" value="submit">SUBMIT</button> 
            <!-- <input type="submit" value="submit"> -->
        </form>
    </div>
    
</div>   
    
        
    
    {% else %}

        <a href="/users/create-account">Create an account to write a story! Click here.</a>

    {% endif %}

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}    
{% load static %}

<!-- everything from h2 tag goes in content block in base template -->

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} # replaces block stylesheets in base.html

{% block content %}

    <div class="centred">   
        <p>The SC Discovery Project is an open source site where artists can submit their pieces and find a community amongst likeminded
            people. We have a pipeline dream to turn this space into one where you can connect with others and comment directly, but at the moment
            The SC Discovery Project is a little corner of the internet where you can browse incredible artworks from up-and-coming artists.
        </p>
        
        {% if request.user.is_authenticated %}
            <p>Got a piece of art you'd like to share?</p>
            <a href="{% url 'news:newStory' %}"><button class="my-button">Submit here!</button></a>
        {% endif %}

        

    </div>

    <h2>Latest Submissions</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div class="centred" id="browse-categories">

        <h6>Browse submissions by category!</h6>

        <a href="{% url 'news:category' %}"><button class="my-button">All Categories</button></a>
        <a href="{% url 'news:digital' %}"><button class="my-button">Digital</button></a>
        <a href="{% url 'news:photography' %}"><button class="my-button">Photography</button></a>
        <a href="{% url 'news:painting' %}"><button class="my-button">Painting</button></a>
    
    </div>

    <h2>All submissions</h2>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/storiesByCategory.html
{% extends "base.html" %}    
{% load static %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}


<div>

{% if all_categories %}


    <h5>Digital</h5>
    {% if Digital %}
    {% for story in Digital_sneak_peek %}
        {% include "./storyCard.html" %}
    {% endfor %}
    {% else %}
        <p>No stories for this category!</p>
    {% endif %}
    <a href="{% url 'news:digital' %}">View All Digital Submissions</a>

    <h5>Photography</h5>
    {% if Photography %}
    {% for story in Photography_sneak_peek %}
        {% include "./storyCard.html" with story=story position=forloop.counter %}
    {% endfor %}
    
    {% else %}
        <p>No stories for this category!</p>
    {% endif %}
    <a href="{% url 'news:photography' %}">View all Photography Submissions</a>


    <h5>Painting</h5>
    {% if Painting %}
    {% for story in Painting_sneak_peek %}
        {% include "./storyCard.html" with story=story position=forloop.counter %}
    {% endfor %}
    
    {% else %}
        <p>No stories for this category!</p>
    {% endif %}
    <a href="{% url 'news:painting' %}">View all Painting Submissions</a>
        
    

{% endif %}
{% endblock %}    

</div>

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>Artist: {{ story.author }}</h4>
    <div id="story-content">
        <!-- add conditional statement to use the defined story image, the placeholder image from database, or the default if no conditions matched -->
        {% if story.story_img %}
            <img src="../media/{{  story.story_img  }}">
        {% else %}
            <img src="../media/images/default_story.jpg"> 
        {% endif %} 

        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id%}">
        {% if story.story_img %}
            <img src="/news/media/{{  story.story_img  }}">
        {% else %}
            <img src="/news/media/images/default_story.jpg"> 
        {% endif %} 
            <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <p>{{  story.category  }}</p>
        </div>
    </a>
</div>